In [1]:
import torch

# Introduction

- **What is it?**  
  A tensor is a multidimensional data structure provided by PyTorch.

- **What is it used for?**  
  - Tensors are used to store data (e.g., images and feature vectors).  
  - They serve as the input and output of PyTorch neural networks.  
  - Neural network parameters are stored in tensors.  

- **What are the main attributes of a tensor?**  
  - **`size`**: Describes the length of each dimension.  
  - **`dtype`**: Specifies the type of the scalars stored in the tensor (e.g., float, int, or complex).  
  - **`device`**: Indicates the device where the tensor is stored in memory (typically CPU or GPU).  
  - **`dim`**: Represents the number of dimensions of the tensor.  

- **Why use tensors instead of Python lists?**  
  The data within a tensor is stored contiguously in memory, enabling fast computations.  

Tensors are a generalization of matrices (which are 2-dimensional data structures) to n-dimensional data structures.  

Formally, a 3D tensor $ t $ of size $((n, m, p))$ is a family of scalars indexed by three integers $( i, j, k )$:  
$$
t = \big( t[i][j][k] \big)_{0 \leq i < n, \; 0 \leq j < m, \; 0 \leq k < p}
$$

To access an element of $t $, you need to specify 3 indices $(i, j, k)$, just as you need to specify 2 indices to access an element of a matrix. This definition can be generalized to n-dimensional tensors.  

<img src="img_tensors.png" alt="Description de l'image" width="400" height="300">  
<p>Source: <a href="https://medium.com/@xinyu.chen/intuitive-understanding-of-tensors-in-machine-learning-33635c64b596" target="_blank">Medium - Intuitive Understanding of Tensors in Machine Learning</a></p>


In [13]:
# Example of a tensor
t = torch.rand((2,3,4))
print(t)
print(t.size())
print(t.dtype)
print(t.device)
print(t.ndim)

tensor([[[0.8928, 0.8570, 0.8314, 0.7321],
         [0.5824, 0.2779, 0.2077, 0.1805],
         [0.2884, 0.4306, 0.7868, 0.6558]],

        [[0.2557, 0.5661, 0.0519, 0.6214],
         [0.7361, 0.5819, 0.6861, 0.5169],
         [0.9123, 0.3182, 0.3905, 0.5218]]])
torch.Size([2, 3, 4])
torch.float32
cpu
3


# Create and Initialize Tensors

## Creating Tensors from Scratch

**In which situations are tensors created from scratch?**  
For example, to test a program, instead of processing real data, you might create your own tensor, perhaps a random one. Tensors often need to be initialized randomly in neural networks.

### Create n-dimensional tensors:

- **torch.zeros**:  
    - **Input**: a size  
    - **Output**: a tensor filled with zeros  

- **torch.ones**:  
    - **Input**: a size  
    - **Output**: a tensor filled with ones  

- **torch.eye**:  
    - **Input**: 1 integer for a square matrix, or 2 integers for a rectangular matrix  
    - **Output**: a matrix with ones on the diagonal and zeros elsewhere  

- **torch.rand**:  
    - **Input**: a size  
    - **Output**: a tensor with scalars sampled uniformly at random in \([0, 1]\)  

- **torch.randn**:  
    - **Input**: a size  
    - **Output**: a tensor with scalars sampled from the standard normal distribution   

In [14]:
# Examples 

# size for a 2d tensor
size_mat = (3,3)
# size for a 3d tensor
size_3d_tensor = (2,3,3)

In [15]:
# torch.zeros
print("torch.zeros:")
t = torch.zeros(size_mat)
print(t)
t = torch.zeros(size_3d_tensor)
print(t)

torch.zeros:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])


In [45]:
# torch.ones 
print("torch.ones:")
t = torch.ones(size_mat)
print(t)
t = torch.ones(size_3d_tensor)
print(t)

torch.ones:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


In [46]:
# torch.eye
print("torch.eye:")
t = torch.eye(3,8)
print(t)

torch.eye:
tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0.]])


In [47]:
# torch.rand
print("torch.rand:")
t = torch.rand(size_mat)
print(t)
t = torch.rand(size_3d_tensor)
print(t)

torch.rand:
tensor([[0.8839, 0.3826, 0.4673],
        [0.4336, 0.3027, 0.3050],
        [0.1909, 0.0944, 0.7962]])
tensor([[[0.2130, 0.3661, 0.9635],
         [0.0976, 0.6335, 0.4093],
         [0.4439, 0.9078, 0.7420]],

        [[0.2697, 0.2037, 0.4582],
         [0.9020, 0.4937, 0.7643],
         [0.6405, 0.9021, 0.9819]]])


In [48]:
# torch.randn
print("torch.randn:")
t = torch.randn(size_mat)
print(t)
t = torch.randn(size_3d_tensor)
print(t)

torch.randn:
tensor([[ 0.1899,  0.3141,  1.7698],
        [-0.1104, -0.8260, -0.2686],
        [-0.0931, -0.1995, -0.3204]])
tensor([[[ 2.0434, -1.1787, -0.5447],
         [-0.2331,  1.0554, -0.0523],
         [ 0.1266, -0.0477, -0.4608]],

        [[-0.8478,  0.9271, -0.3248],
         [-0.2420,  0.5935, -0.2291],
         [-0.1701, -1.1707,  2.4336]]])


### Create 1D tensors:  

- **torch.linspace**:  
    - **Input**: a start, an end, and a number of steps  
    - **Output**: Creates a one-dimensional tensor of size `steps`, with values evenly spaced from start to end, inclusive  

- **torch.arange**:  
    - **Input**: a start, an end, and a step  
    - **Output**: Creates a one-dimensional tensor with values `start`, `start + step`, `start + 2*step`, ..., while `start + k * step < end` 

In [16]:
# linspace
print(torch.linspace(1,10,10))
print(torch.linspace(0.2,1.3,25))

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor([0.2000, 0.2458, 0.2917, 0.3375, 0.3833, 0.4292, 0.4750, 0.5208, 0.5667,
        0.6125, 0.6583, 0.7042, 0.7500, 0.7958, 0.8417, 0.8875, 0.9333, 0.9792,
        1.0250, 1.0708, 1.1167, 1.1625, 1.2083, 1.2542, 1.3000])


In [50]:
# arange
print(torch.arange(1,10,1))
print(torch.arange(3,20,4))

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([ 3,  7, 11, 15, 19])


## Creating Tensors from existing data

### From Python/Numpy/Pandas to Tensors

**In which situations should you convert a data structure into a tensor?**  
If you have some NumPy arrays or Python lists that you want to use as data to train your neural network with PyTorch, you will need to convert them into tensors.

For that, we will use the function `torch.tensor`.

**Which data structures can we convert into tensors with the function `torch.tensor`?** 

Some important ones:

- Python lists  
- Python scalars  
- NumPy arrays  
- Pandas DataFrames  

In [5]:
# From a Python list 
l = [1,2,3]
t = torch.tensor(l)
print("from a list:",t)

# From a matrix 
m = [[1,2,3],[4,5,6]]
t = torch.tensor(m)
print("from a matrix",t)

# From a Python scalar
x = 861 
t = torch.tensor(x)
print("from a scalar:",t)

# From a Numpy array
import numpy as np
arr = np.linspace(0,50,6)
t = torch.tensor(arr)
print("from a scalar:",t)
# Remark: You can convert a tensor into a numpy array by doing t.numpy()

from a list: tensor([1, 2, 3])
from a matrix tensor([[1, 2, 3],
        [4, 5, 6]])
from a scalar: tensor(861)
from a scalar: tensor([ 0., 10., 20., 30., 40., 50.], dtype=torch.float64)


### From Tensor to Tensor: Converting Scalar Dtype

There are two ways to convert the type of the elements in a tensor:  
- `torch.tensor(t, dtype=name_of_the_type)`: It **creates a new tensor** by copying `t` and converting the elements into the desired type.  
- `torch.name_of_the_type()`: It **creates a new tensor** by copying `t` and converting the elements into the desired type.

In [8]:
# Example for torch.tensor(t,dtype=name_of_the_type)
t = torch.tensor([[1,2],[3,4]] , dtype=torch.float)
print(t.type())
t2 = torch.tensor(t,dtype=torch.long)
print(t2.type())
print("Are t and t2 the same in memory ?",t.data_ptr() == t2.data_ptr())

torch.FloatTensor
torch.LongTensor
Are t and t2 the same in memory ? False


/var/folders/rj/jncxshgs6tjb572dxm8jzvwc0000gn/T/ipykernel_82332/4016059229.py:4: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  t2 = torch.tensor(t,dtype=torch.long)


In [9]:
# Example for torch.name_of_the_type()
t = torch.tensor([[1,2],[3,4]] , dtype=torch.float)
print(t.type())
t2 = t.long()
print(t2.type())
print("Are t and t2 the same in memory ?",t.data_ptr() == t2.data_ptr())

torch.FloatTensor
torch.LongTensor
Are t and t2 the same in memory ? False


# Operations on tensors

## Basic Operations

Some common operations on tensors:

- **Addition (elementwise)**:  
    - **Input**: `t`, `t'` two tensors with equal size  
    - **Output**: `t + t'`  

- **Multiplication by a scalar (elementwise)**:  
    - **Input**: `t` a tensor, `a` a scalar  
    - **Output**: `a * t`, where each element of `t` is multiplied by `a`  

- **Multiplication by a tensor (elementwise)**:  
    - **Input**: `t`, `t'` two tensors with equal size  
    - **Output**: `t * t'`, where each element of `t` is multiplied by the corresponding element of `t'`  

- **Multiplication of 2D tensors (matrix multiplication)**:  
    - **Input**: `t`, `t'` two 2D tensors  
    - **Output**: `t @ t'`, the matrix multiplication of `t` and `t'`

In [54]:
# Examples
t = torch.ones((3,3))
print("t:",t)
print("t+t:",t+t)
print("12*t:",12*t)
t2 = torch.eye(3)
print("t2:",t2)
print("t*t2:",t*t2)
print("t@t2:",t@t2)

t: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
t+t: tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
12*t: tensor([[12., 12., 12.],
        [12., 12., 12.],
        [12., 12., 12.]])
t2: tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
t*t2: tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
t@t2: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


## Functions for Manipulating Tensor Dimensions

Some functions for working with tensor dimensions:

- **reshape**:  
    - **Input**: A tensor and a compatible size (the number of elements must be the same)  
    - **Output**: A tensor with the new size, containing the same values as the original tensor  

- **squeeze**:  
    - **Input**: A tensor and the index of the dimension of size 1 you want to squeeze  
    - **Output**: A tensor with the specified dimension of size 1 removed  

- **unsqueeze**:  
    - **Input**: A tensor and the index at which to insert the singleton dimension  
    - **Output**: A tensor with a new dimension of size one inserted at the specified position  

- **unbind**:  
    - **Input**: A tensor  
    - **Output**: A tuple of all slices along a given dimension, with that dimension removed  

- **swapaxes**:  
    - **Input**: A tensor, `axis1`, and `axis2`  
    - **Output**: A tensor with the specified dimensions (`axis1` and `axis2`) swapped  

- **cat**:  
    - **Input**: A sequence of tensors and the index of the dimension along which to concatenate the tensors. All tensors must have the same shape, except in the concatenating dimension  
    - **Output**: Concatenates the given sequence of tensors along the specified dimension

In [10]:
# Example for reshape
t = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(t)
print(t.reshape((3, 2)))

# As the number of elements must be the same, we let torch infer one dimension by leaving it at -1
print(t.reshape((3, -1)))
print(t.reshape((-1,)))
print(t.reshape(1, 1, 2, 3))


tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([1, 2, 3, 4, 5, 6])
tensor([[[[1, 2, 3],
          [4, 5, 6]]]])


In [56]:
# Example for squeeze
t = torch.tensor([[1,2,3,4,5]])
print(t)
print(t.size())

t2 = torch.squeeze(t,0)
print(t2)
print(t2.size())

print()

t = torch.tensor([[1],[2],[3],[4],[5]])
print(t)
print(t.size())

t2 = torch.squeeze(t,1)
print(t2)
print(t2.size())


tensor([[1, 2, 3, 4, 5]])
torch.Size([1, 5])
tensor([1, 2, 3, 4, 5])
torch.Size([5])

tensor([[1],
        [2],
        [3],
        [4],
        [5]])
torch.Size([5, 1])
tensor([1, 2, 3, 4, 5])
torch.Size([5])


In [57]:
# Example of unsqueeze
t = torch.tensor([1,2,3,4])
print(t)
print(torch.unsqueeze(t,0))
print(torch.unsqueeze(t,1))
# for example, it is used for adding a batch dimension as a first dimension : t.unsqueeze(0)

tensor([1, 2, 3, 4])
tensor([[1, 2, 3, 4]])
tensor([[1],
        [2],
        [3],
        [4]])


In [58]:
# Example of unbind
t = torch.tensor([[1,2,3],
                  [4,5,6],
                  [7,8,9]]
                )
print(t)
print(torch.unbind(t,0))
print(torch.unbind(t,1))

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
(tensor([1, 2, 3]), tensor([4, 5, 6]), tensor([7, 8, 9]))
(tensor([1, 4, 7]), tensor([2, 5, 8]), tensor([3, 6, 9]))


In [59]:
# Example of swapaxes 
t = torch.tensor([[1,2,3],
                  [4,5,6],
                  [7,8,9]]
                )
print(t)
print(torch.swapaxes(t,0,1))
# An example of application:
# if you receiv a an image whith size (3,28,28) where 3 are the canals then to swap the canals 
# to the last dimension you can do torch.swapaxes(t,0,2) and otain a tensor of size (28,28,3)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])


In [60]:
# Example for cat
t = torch.tensor([[1,2,3],
                  [4,5,6],
                  [7,8,9]]
                )
t2 = torch.tensor([[10,11,12],
                   [13,14,15],
                   [16,17,18]
                   ]
                )

# Concatenate the rows
print(torch.cat([t,t2],0))
# Concatenate the cols
print(torch.cat([t,t2],1))

# An example of application:
# Create a batch from a sequence of datapoints

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])
tensor([[ 1,  2,  3, 10, 11, 12],
        [ 4,  5,  6, 13, 14, 15],
        [ 7,  8,  9, 16, 17, 18]])


## Reduction Operations

Some functions for extracting data from tensors:

- **sum**:  
    - **Input**: A tensor  
    - **Output**: The sum of all scalars in the tensor  

- **mean**:  
    - **Input**: A tensor with floating-point scalars  
    - **Output**: The mean of the scalars in the tensor  

- **amax**:  
    - **Input**: A tensor and a dimension  
    - **Output**: The maximum value of each slice of the input tensor along the specified dimension

In [61]:
t = torch.tensor([[1,2],
                  [3,4]],dtype=torch.float)
print(t.sum())
print(t.mean())
# for each row we compute the max value
print(t.amax(1))
# for each col we compute the max value
print(t.amax(0))

tensor(10.)
tensor(2.5000)
tensor([2., 4.])
tensor([3., 4.])


## Math Functions

Some important operations:

- **allclose** (used to test the equality between two tensors):  
    - **Input**: Two tensors, `t1` and `t2`, of the same size  
    - **Output**: `True` if all elements of `t1` and `t2` are close enough  

- **sign**:  
    - **Input**: A tensor  
    - **Output**: For each element `x`, returns -1 if `x < 0`, 0 if `x = 0`, and 1 if `x > 0`

In [62]:
t1 = torch.zeros((3,3),dtype=torch.float)
t2 = torch.ones((3,3),dtype=torch.float)

# Example for allclose
print(torch.allclose(t1,t2))
print(torch.allclose(t1,t2/100000000))

# Example for sign 
t = torch.randn((3,3))
print(t)
print(torch.sign(t))

False
True
tensor([[ 0.4929, -1.3010, -2.9695],
        [ 2.5780, -0.6066,  0.7551],
        [ 1.3309, -0.8695, -0.8887]])
tensor([[ 1., -1., -1.],
        [ 1., -1.,  1.],
        [ 1., -1., -1.]])


# References
- https://pytorch.org/docs/stable/torch.html#tensors